<?php
declare(strict_types=1);
namespace Kontact;

require_once __DIR__ . '/../lib/bootstrap.php';
require_once __DIR__ . '/../lib/Database.php';

header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store');

// Token storage (file-based to avoid schema changes)
$tokFile = __DIR__ . '/../storage/secret/firewall_feed_token.txt';
if (!is_dir(dirname($tokFile))) {
    @mkdir(dirname($tokFile), 0775, true);
}

// Generate token on first run if missing
if (!is_file($tokFile)) {
    $tok = bin2hex(random_bytes(24));
    @file_put_contents($tokFile, $tok);
    @chmod($tokFile, 0640);
}
$serverToken = @trim((string)@file_get_contents($tokFile));

$clientToken = (string)($_GET['token'] ?? '');
if (!is_string($serverToken) || $serverToken === '' || !hash_equals($serverToken, $clientToken)) {
    http_response_code(403);
    header('Content-Type: text/plain; charset=utf-8');
    echo "forbidden\n";
    exit;
}

$fmt = strtolower((string)($_GET['format'] ?? 'plain'));

$db = new Database($GLOBALS['cfg']);
$rows = $db->fetchAll("SELECT ip FROM kontact_blocklist WHERE (expires_at IS NULL OR expires_at > NOW()) GROUP BY ip ORDER BY ip ASC");

// Unique, normalized
$ips = [];
foreach ($rows as $r) {
    $ip = trim((string)$r['ip']);
    if ($ip !== '' && !isset($ips[$ip])) $ips[$ip] = true;
}
$list = array_keys($ips);

// Output
if ($fmt === 'ipset') {
    header('Content-Type: text/plain; charset=utf-8');
    echo "# ipset-restore snippet generated by Kontact\n";
    echo "create kontact_blocklist4 hash:ip family inet hashsize 1024 maxelem 65536 -exist\n";
    echo "flush kontact_blocklist4\n";
    foreach ($list as $ip) {
        if (strpos($ip, ':') === false) {
            echo "add kontact_blocklist4 $ip -exist\n";
        }
    }
    echo "create kontact_blocklist6 hash:ip family inet6 hashsize 1024 maxelem 65536 -exist\n";
    echo "flush kontact_blocklist6\n";
    foreach ($list as $ip) {
        if (strpos($ip, ':') !== false) {
            echo "add kontact_blocklist6 $ip -exist\n";
        }
    }
    exit;
}

// Default: plain (one IP per line), works as a generic feed for many control panels
header('Content-Type: text/plain; charset=utf-8');
foreach ($list as $ip) { echo $ip, "\n"; }
